name: reusable wf
on: 
    workflow_call:
        inputs:
            artifact-name:
              description: the name
              required: false
              default: dist
              type: string
jobs: 
    reuseableJob:
        runs-on: ubuntu-latest
        steps:
            - name: get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-name }}
            - name: list files
              run: ls 
            - name: What
              run: echo "what"
