name: reusable wf
on: 
    workflow_call:
        inputs:
            artifact-dame:
              description: the name
              required: false
              default: dist
              type: string
        outputs:
            result:
              description: the result of the operation
              value: ${{jobs.reuseableJob.outputs.outcome}}
              

jobs: 
    reuseableJob:
        outputs:
            outcome: ${{steps.set-results.outputs.step-resultPP}}
        runs-on: ubuntu-latest
        steps:
            - name: get Code
              uses: actions/download-artifact@v3
              with:
                name: ${{ inputs.artifact-dame }}
            - name: list files
              run: ls 
            - name: What
              run: echo "what"
            - name: set result output
              id: set-results
              run: echo "::set-output name=step-resultPP::success"
