name: matric
on: push
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-versions: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{matrix.operating-system}}
        steps:
            - name: get Code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: ${{matrix.node-versions}}
            - name: Install dependencies
              run: npm ci
            - name: build project
              run: npm run build